version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test: # this can be any name you choose
  executor: node/defect # use the default excutor defined within the orb
  steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        command: npm test
        name: Run tests
    - run:
        command: npm build
        name: Build app
wrokflows:
  test_my_app:
    jobs:
      - build_and_test
    